title: [HungerForData]
description: [Your data science hub by Phillip Hungerford]
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

<link rel="shortcut icon" type="image/x-icon" href="https://emojipedia.org/man-scientist/#:~:text=Mudar%20o%20idioma-,%F0%9F%91%A8%E2%80%8D%F0%9F%94%AC,-Man%20Scientist">